/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpeakersRouteImport } from './routes/speakers'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as BreakoutsRouteImport } from './routes/breakouts'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AbstractsRouteImport } from './routes/abstracts'
import { Route as IndexRouteImport } from './routes/index'

const SpeakersRoute = SpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const BreakoutsRoute = BreakoutsRouteImport.update({
  id: '/breakouts',
  path: '/breakouts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AbstractsRoute = AbstractsRouteImport.update({
  id: '/abstracts',
  path: '/abstracts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abstracts': typeof AbstractsRoute
  '/announcements': typeof AnnouncementsRoute
  '/breakouts': typeof BreakoutsRoute
  '/feedback': typeof FeedbackRoute
  '/gallery': typeof GalleryRoute
  '/partners': typeof PartnersRoute
  '/profile': typeof ProfileRoute
  '/schedule': typeof ScheduleRoute
  '/speakers': typeof SpeakersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abstracts': typeof AbstractsRoute
  '/announcements': typeof AnnouncementsRoute
  '/breakouts': typeof BreakoutsRoute
  '/feedback': typeof FeedbackRoute
  '/gallery': typeof GalleryRoute
  '/partners': typeof PartnersRoute
  '/profile': typeof ProfileRoute
  '/schedule': typeof ScheduleRoute
  '/speakers': typeof SpeakersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abstracts': typeof AbstractsRoute
  '/announcements': typeof AnnouncementsRoute
  '/breakouts': typeof BreakoutsRoute
  '/feedback': typeof FeedbackRoute
  '/gallery': typeof GalleryRoute
  '/partners': typeof PartnersRoute
  '/profile': typeof ProfileRoute
  '/schedule': typeof ScheduleRoute
  '/speakers': typeof SpeakersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abstracts'
    | '/announcements'
    | '/breakouts'
    | '/feedback'
    | '/gallery'
    | '/partners'
    | '/profile'
    | '/schedule'
    | '/speakers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abstracts'
    | '/announcements'
    | '/breakouts'
    | '/feedback'
    | '/gallery'
    | '/partners'
    | '/profile'
    | '/schedule'
    | '/speakers'
  id:
    | '__root__'
    | '/'
    | '/abstracts'
    | '/announcements'
    | '/breakouts'
    | '/feedback'
    | '/gallery'
    | '/partners'
    | '/profile'
    | '/schedule'
    | '/speakers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbstractsRoute: typeof AbstractsRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  BreakoutsRoute: typeof BreakoutsRoute
  FeedbackRoute: typeof FeedbackRoute
  GalleryRoute: typeof GalleryRoute
  PartnersRoute: typeof PartnersRoute
  ProfileRoute: typeof ProfileRoute
  ScheduleRoute: typeof ScheduleRoute
  SpeakersRoute: typeof SpeakersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/speakers': {
      id: '/speakers'
      path: '/speakers'
      fullPath: '/speakers'
      preLoaderRoute: typeof SpeakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breakouts': {
      id: '/breakouts'
      path: '/breakouts'
      fullPath: '/breakouts'
      preLoaderRoute: typeof BreakoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abstracts': {
      id: '/abstracts'
      path: '/abstracts'
      fullPath: '/abstracts'
      preLoaderRoute: typeof AbstractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbstractsRoute: AbstractsRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  BreakoutsRoute: BreakoutsRoute,
  FeedbackRoute: FeedbackRoute,
  GalleryRoute: GalleryRoute,
  PartnersRoute: PartnersRoute,
  ProfileRoute: ProfileRoute,
  ScheduleRoute: ScheduleRoute,
  SpeakersRoute: SpeakersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
